Loek/cleanup
lonkaars/crepe pull request #26
Opened 2024-11-07 20:24 UTC by lonkaars

The following files need to be checked for code style compliance **in their entirety**:

- src/crepe/Asset.cpp
- src/crepe/Asset.h
- src/crepe/api/BehaviorScript.cpp
- src/crepe/api/BehaviorScript.h
- src/crepe/api/BehaviorScript.hpp
- src/crepe/api/Config.h
- src/crepe/api/Script.cpp
- src/crepe/api/Script.h
- src/crepe/api/Script.hpp
- src/crepe/facade/Sound.cpp
- src/crepe/facade/Sound.h
- src/crepe/facade/SoundContext.cpp
- src/crepe/facade/SoundContext.h
- src/crepe/system/ScriptSystem.cpp
- src/crepe/system/ScriptSystem.h
- src/crepe/system/System.h
- src/crepe/util/LogColor.cpp
- src/crepe/util/LogColor.h
- src/crepe/util/fmt.cpp
- src/crepe/util/fmt.h
- src/crepe/util/log.cpp
- src/crepe/util/log.h
- src/example/audio_internal.cpp
- src/example/log.cpp
- src/example/script.cpp
- src/test/audio.cpp
- src/test/dummy.cpp

I also changed an option in `.clang-format` which caused changes in files that are not mine, these files don't need to be checked.

2024-11-13 07:44 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/util/LogColor.h#L9
Waarom definieer je hier een default constructor? Wat is het nut hiervan?

2024-11-13 08:01 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/util/LogColor.h#L6
Ik mis hier Doxygen comments (o.a. boven de klasse en boven meerdere methodes). Daarnaast worden parameters niet gedocumenteerd (dat moet ook worden gedaan).

2024-11-13 08:03 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/util/log.h#L36
Van LogColor maak je wel een klasse, maar van log en fmt niet. Is dat een bewuste keuze? Waarom niet gewoon een klasse zoals je zou verwachten in een object georiënteerde taal?

2024-11-13 08:09 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/util/LogColor.cpp#L36
Waarom kies je hier voor een C-achtige oplossing? Ik zou hier gewoon iets dergelijks als `this->code += "\e[" + to_string(code) + "m"` gebruiken. Als je dit gebruikt kan stringf() in fmt.h/.cpp zelfs helemaal weg :)

2024-11-13 08:12 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/util/LogColor.cpp#L23
Hier kun je beter `nullptr` gebruiken i.p.v. `NULL` (dat is namelijk modern C++).

2024-11-13 08:24 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/util/fmt.cpp#L9
Waarom gebruik je hier (en op verschillende andere plekken) va_list en niet perfect forwarding? PS Ik kende va_list zelf niet, maar ik heb (na wat Googlen) begrepen dat dit de C-oplossing voor perfect forwarding is.

2024-11-13 08:30 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/util/log.cpp#L37
Waarom gebruik je hier (alweer) C-achtige oplossingen? Waarom gebruik je niet gewoon streams (zoals je zou verwachten in modern C++)?
Je zou dan `fwrite(...)` en `fflush(...)` vervangen door `cout << out` en `cout.flush()`.

2024-11-13 08:35 UTC, Max-001 commented
Kun je uitleg geven waarvoor de Exception klasse dient? Het lijkt alsof je graag `printf` achtige syntax wil kunnen gebruiken en dat de Exception klasse daar alleen voor dient (terwijl je in modern C++ juist geen `printf` achtige syntax verwacht).

2024-11-13 08:56 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/Asset.h#L29
Veranderen `src` en `file` gedurende het programma (nee toch)? Zo nee, dan moeten ze const worden.

2024-11-13 08:58 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/Asset.h#L24
Zowel `read` als `canonical` zijn volgens mij setters. Ik mis de `set_` prefix zoals beschreven in de code standaard.
Daarnaast zijn de deze methodes niet const, maar volgens moet dat wel (const-correctness).
Check dit bij iedere file aub.

2024-11-13 08:59 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/Asset.h#L23
De returns zijn niet gedocumenteerd (Doxygen). Dit moet, denk ik, wel.

2024-11-13 09:00 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/Asset.cpp#L10
Hier moet je de initializer list gebruiken.

2024-11-13 09:03 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/Asset.h#L4
Is deze include hier niet overbodig?

2024-11-13 09:08 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/api/BehaviorScript.h#L12
Ik mis Doxygen.

2024-11-13 09:10 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/api/BehaviorScript.h#L19
Waarom is hier een virtual default destructor nodig?

2024-11-13 09:28 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/system/ScriptSystem.h#L17
Moet deze getter niet const zijn?

2024-11-13 09:33 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/api/BehaviorScript.h#L13
Hoort BehaviorScript niet het ID te ontvangen in zijn constructor en die door te geven aan Component?

2024-11-13 09:36 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/system/System.h#L10
Waar is deze default constructor goed voor?

2024-11-13 09:40 UTC, Max-001 requested changes
Ik heb wat commentaar achter gelaten. Het eerste gedeelte van het commentaar gaat over het gebruik van niet modern C++ (m.b.t. het gebruik van C-achtige constructies). Het tweede gedeelte van het commentaar gaat over van alles en nog wat.
Al het commentaar wat ik heb achtergelaten, geldt niet alleen voor die specifieke file, maar ook voor alle andere files (check dus aub iedere file van deze PR).
Als je het commentaar hebt verwerkt, kijk ik er graag nog een keer overheen want verschillende files heb ik nog niet helemaal bekeken.

2024-11-13 13:37 UTC, lonkaars commented
> https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/util/log.cpp#L37
> 
> 
> Waarom gebruik je hier (alweer) C-achtige oplossingen? Waarom gebruik je niet gewoon streams (zoals je zou verwachten in modern C++)?
> Je zou dan `fwrite(...)` en `fflush(...)` vervangen door `cout << out` en `cout.flush()`.

Dit is een bewuste keuze omdat logging met strings werkt, geen string streams. Ik kan strings direct naar standard output schrijven en flushen, en dit is de eenvoudigste oplossing die ik hiervoor kan bedenken. Ik heb inmiddels de rest van de logging bijgewerkt om inderdaad wel meer "moderne C++ dingen" te gebruiken, maar ik heb persoonlijk gewoon een hekel aan streams voor dingen printen in C++.

2024-11-13 13:40 UTC, lonkaars commented
> Kun je uitleg geven waarvoor de Exception klasse dient? Het lijkt alsof je graag `printf` achtige syntax wil kunnen gebruiken en dat de Exception klasse daar alleen voor dient (terwijl je in modern C++ juist geen `printf` achtige syntax verwacht).

Ik had de `Exception` klasse origineel inderdaad gemaakt omdat ik de `printf`-syntax wou gebruiken bij het aanmaken van foutmeldingen, maar ben er dus zojuist achter gekomen dat `std::format` bestaat en heb dit nu toegepast. Ik weet eerlijk gezegd niet of het (niet) slim of nuttig is om nu nog zelf een exception-klasse te hebben of dat we beter overal `std::runtime_exception` met een `std::format` message kunnen gebruiken...

2024-11-13 13:47 UTC, lonkaars commented
> https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/api/BehaviorScript.h#L13
> 
> 
> Hoort BehaviorScript niet het ID te ontvangen in zijn constructor en die door te geven aan Component?

en

> https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/system/System.h#L10
> 
> 
> Waar is deze default constructor goed voor?

heb ik opgelosd in #32

2024-11-13 16:45 UTC, Max-001 commented
Ik ga morgen uitgebreid deze PR (nogmaals) bekijken. Maar ik probeerde nu al even snel te builden (alle examples) en toen liep ik hier tegenaan:
![image](https://github.com/user-attachments/assets/65bfdd62-e2c1-4f8c-90d5-99b05813ab7d)
![image](https://github.com/user-attachments/assets/ff985558-4908-4fe3-9dcd-27c55e4b82da)

Het lijkt alsof er iets gewijzigd aan het GameObject. Zou je die wijziging dan ook door willen voeren in de rest van de (example) code (de master moet immers altijd te compileren zijn)?

2024-11-14 07:24 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/8600b8a29351aae26ec7b22f84aeeef92d8cb421/src/crepe/api/Script.cpp#L1
Kan Script.cpp niet gewoon weg? Er staat nu namelijk helemaal geen code in. Of is dit voor toekomstig gebruik?

2024-11-14 07:27 UTC, Max-001 commented
Thnx voor het oplossen van de build errors hierboven!
![image](https://github.com/user-attachments/assets/7e49f47e-d7bc-4ed6-ba6a-f83674c42f68)
Echter, nu krijg ik een build error bij de particle example.

2024-11-14 07:48 UTC, Max-001 commented
> > https://github.com/lonkaars/crepe/blob/daf2a06ac778f203e1473431afe09476e8182f65/src/crepe/util/log.cpp#L37
> > 
> > Waarom gebruik je hier (alweer) C-achtige oplossingen? Waarom gebruik je niet gewoon streams (zoals je zou verwachten in modern C++)?
> > Je zou dan `fwrite(...)` en `fflush(...)` vervangen door `cout << out` en `cout.flush()`.
> 
> Dit is een bewuste keuze omdat logging met strings werkt, geen string streams. Ik kan strings direct naar standard output schrijven en flushen, en dit is de eenvoudigste oplossing die ik hiervoor kan bedenken. Ik heb inmiddels de rest van de logging bijgewerkt om inderdaad wel meer "moderne C++ dingen" te gebruiken, maar ik heb persoonlijk gewoon een hekel aan streams voor dingen printen in C++.

Thnx voor je aanpassingen in de rest van de logging! Het ziet er qua mij betreft al stukken beter uit (en het is voor mijn gevoel nu ook beter leesbaar/begrijpbaar).
Ik snap dat je voorkeur uitgaat naar het niet gebruiken van streams voor het schrijven van/naar CLI. Toch zou ik graag streams gebruiken omdat dat hetgeen is wat tijdens de C++ lessen is aangeraden.

2024-11-14 07:54 UTC, Max-001 commented
> > Kun je uitleg geven waarvoor de Exception klasse dient? Het lijkt alsof je graag `printf` achtige syntax wil kunnen gebruiken en dat de Exception klasse daar alleen voor dient (terwijl je in modern C++ juist geen `printf` achtige syntax verwacht).
> 
> Ik had de `Exception` klasse origineel inderdaad gemaakt omdat ik de `printf`-syntax wou gebruiken bij het aanmaken van foutmeldingen, maar ben er dus zojuist achter gekomen dat `std::format` bestaat en heb dit nu toegepast. Ik weet eerlijk gezegd niet of het (niet) slim of nuttig is om nu nog zelf een exception-klasse te hebben of dat we beter overal `std::runtime_exception` met een `std::format` message kunnen gebruiken...

Ik ben het met je eens dat het slimmer is om `std::format` te gebruiken (i.p.v. een hele eigen Exception klasse te maken). Ik zal dit als resolved aanmerken.

2024-11-14 10:11 UTC, Max-001 commented
https://github.com/lonkaars/crepe/blob/8600b8a29351aae26ec7b22f84aeeef92d8cb421/src/crepe/api/Config.h#L12
Waarom is hier een default destructor nodig? Volgens mij kan die gewoon weg.

2024-11-14 10:43 UTC, Max-001 requested changes
Ik hoop dat ik je niet overdonder met alle comments. Het is gewoon een gigantische PR en daardoor ook gigantisch veel comments.

Ik gok dat ik nu net iets meer dan de helft van alles files heb kunnen reviewen. Boven alle files die ik nog niet gereviewed heb, heb ik een comment achtergelaten die dat aangeeft.

Het zou fijn zijn als je het commentaar wat ik nu gegeven heb, verwerkt (of er natuurlijk commentaar op terug geeft). Graag het commentaar niet alleen bij die ene file verwerken waar het commentaar bij staat, maar ook in alle andere files (als ik bijvoorbeeld op meerdere plekken /param Doxygen comments mis, dan heb ik dat bij slechts één file aangegeven en dus niet overal opnieuw).

2024-11-14 10:43 UTC, Max-001 commented on src/crepe/system/ScriptSystem.cpp
Ik heb wat commentaar achtergelaten m.b.t. BehavoirScript.h, BehavoirScript.hpp, BehavoirScript.cpp, Script.h, Script.hpp, Script.cpp, ScriptSystem.h én ScriptSystem.cpp. Graag heb ik dat dit commentaar eerst wordt verwerkt, daarna zal ik nog een controle uitvoeren m.b.t. de code standaard.

2024-11-14 10:43 UTC, Max-001 commented on src/crepe/api/Config.h
Wellicht is het beter om dit geen Singelton te maken.

2024-11-14 10:43 UTC, Max-001 commented on src/crepe/api/GameObject.cpp
Gezien de tijd kijk ik nu niet super goed naar deze aanpassing. Graag wil ik hier op een later moment, zodra alles voldoet aan de code standaard, nog eens goed naar kijken.

2024-11-14 10:43 UTC, Max-001 commented on src/crepe/api/GameObject.h
Gezien de tijd kijk ik nu niet super goed naar deze aanpassing. Graag wil ik hier op een later moment, zodra alles voldoet aan de code standaard, nog eens goed naar kijken.

2024-11-15 07:05 UTC, Max-001 commented on src/crepe/Collider.h
> +	using Component::Component;
Als ik using goed begrijp, is dat alleen mogelijk als alle argumenten van de constructor door moeten worden gestuurd naar de afgeleide klasse (Component in dit geval).
Echter, in de praktijk zullen er altijd meer argumenten (dan wat Component z’n constructor kan ontvangen) in de constructor van concrete components staan. Dat komt omdat concrete component altijd data bevat en die data wordt (vrijwel) altijd ge-set via de constructor.

2024-11-15 17:50 UTC, lonkaars commented on src/example/log.cpp
> +	cfg.log.level = Log::Level::TRACE;
Config is en blijft de enige singleton in de applicatie.

2024-11-15 17:54 UTC, lonkaars commented on src/crepe/util/Log.cpp
>  	auto & cfg = Config::get_instance();
De `Log` klasse heeft bewust alleen `static` functies omdat logging overal toegankelijk moet zijn. `Config` refactoren om overal via dependency injection doorgegeven te worden is te veel gedoe.

Ik zie nu dat er een globale beschrijving van `Config` mist maar het idee is dat de game programmeur alleen opties aanpast *voordat* hij/zij de loopmanager start en daarmee de engine "echt" start. Dit was bedacht als alternatief op compile-time constantes omdat de engine straks al gecompileerd is maar de game programmeur nog wel "constantes" aan moet passen.

2024-11-15 18:08 UTC, lonkaars commented on src/crepe/util/LogColor.h
> +	//! Reset color to default foreground and background color
Dit wordt met een `\note` aangegeven omdat deze functies achter elkaar aangeroepen kunnen worden (= method chaining). Dit was makkelijker dan overal de documentatie kopiëren, en houdt de header zelf ook iets leesbaarder. Dit is hoe het er in Doxygen zelf uit ziet:
![image](https://github.com/user-attachments/assets/5062cb4e-14cc-41ea-9403-eb154986f014)

2024-11-15 18:09 UTC, lonkaars commented on src/crepe/util/LogColor.h
>  	LogColor & reset();
`LogColor().reset().str()` returnet de escape sequence om de default achtergrond+tekstkleur te herstellen

2024-11-15 18:14 UTC, lonkaars commented on src/crepe/api/BehaviorScript.h
> +	~BehaviorScript() = default;
`BehaviorScript` wordt aangemaakt door `ComponentManager` (wat mag want er is een `friend` relatie), maar weer opgeruimd door `std::unique_ptr`, dus ik wil hier zeker maken dat de destructor public zal zijn. Dit zorgt anders voor hele nare bugs die de compiler niet opvangt.

Ik weet niet of dit nodig is wanneer ik de destructor van `Component` declareer als `virtual ~Component() = default;` (met `public` zichtbaarheid), maar dat staat sinds een uur geleden ofzo pas in de code standaard. `Component` is niet mijn klasse, dus ik corrigeer dit liever in een andere PR.

2024-11-15 18:26 UTC, lonkaars commented on src/example/log.cpp
> +	Log::logf(Log::Level::ERROR, "error");
Ik heb de Exception klasse net weggehaald, maar ik ga er vanuit dat de loop manager (of een ander ver bovenliggend systeem) alle nog niet opgevangen exceptions kan opvangen en loggen. Of dat het spel moet laten crashen is denk ik nog open voor discussie, maar ik vind én een exception én een log bericht erg veel want exceptions worden niet altijd voor fouten gebruikt die niet op te lossen zijn (= de persoon die hem opvangt bepaalt hoe serieus het probleem is)

2024-11-15 18:27 UTC, lonkaars commented on src/crepe/util/Log.h
> +	 */
`\tparam` is niet relevant want de argumenten worden geforward naar `std::format`

2024-11-15 18:28 UTC, lonkaars commented on src/crepe/util/Log.h
> +		ERROR, //< Fatal errors
Ik heb niet zo veel speciaals te zeggen over deze willekeurig gekozen niveaus en dit was korter :^)

2024-11-15 18:30 UTC, lonkaars commented on src/crepe/Asset.cpp
>  	this->file = std::ifstream(this->src, std::ios::in | std::ios::binary);
Deze hele klasse is gerenoveerd op [`loek/audio`](https://github.com/lonkaars/crepe/tree/loek/audio) dus ga ik hier niet aanpassen ivm merge conflicts

2024-11-15 18:34 UTC, lonkaars commented on src/crepe/Collider.h
> +	using Component::Component;
Ik heb geen actieve herinnering aan het maken van deze aanpassing, maar `using Base::Base` neemt inderdaad de constructor van een basisklasse over. In de praktijk hebben alle componenten meer data nodig dan alleen het game object ID, maar volgensmij is dit nog de super oude Collider van de eerste ECS demo die ik toen (per ongeluk) te vroeg gemerged had naar `master` omdat ik dat dat die klaar en bruikbaar was.

2024-11-15 18:41 UTC, lonkaars commented on src/crepe/ComponentManager.cpp
> +GameObject ComponentManager::new_object(const string & name, const string & tag,
Er moeten nog veel meer opvraag/utility functies komen op `Script`, maar voor nu heb ik alleen de aanpassing dat `next_id` gereset wordt bij het clearen van de componentmanager aangenomen. Over wat er precies moet gebeuren met de `GameObject` instantie als er bijv. `delete_components_by_id` aangeroepen wordt kan ook nog gediscussiëerd worden, maar omdat GameObject zelf niks vast houdt en alleen als doorgeefluik gebruikt wordt denk ik niet dat het voor problemen zal zorgen.

Ik snap alleen niet waarom de game programmeur handmatig de game object id's moet kunnen beheren, dat lijkt mij juist meer werk?

2024-11-15 18:48 UTC, lonkaars commented on src/crepe/api/BehaviorScript.h
> +BehaviorScript & GameObject::add_component<BehaviorScript>();
Dit is een zogehete [explicit (full) template specialization](https://en.cppreference.com/w/cpp/language/template_specialization), en heb ik in BehaviorScript.h gedefiniëerd omdat deze niet binnen de GameObject klassedefinitie gedefiniëerd *kan* worden (moet buiten klasse defnitie), en omdat deze functie dient als een uitzondering voor BehaviorScript (ik vind dat BehaviorScript hier dus verantwoordelijk voor is).

Het vertelt de compiler dat de `GameObject::add_component` functie wanneer het template-argument `BehaviorScript` is een afwijkende implementatie heeft (in dit geval om een reference naar de ComponentManager mee te geven vanuit GameObject). BehaviorScript is het enige component die deze soort rare fratsen uithaalt.

2024-11-15 18:51 UTC, lonkaars commented on src/crepe/api/BehaviorScript.h
> +	ComponentManager & component_manager;
BehaviorScript is de enige uitzondering, en hier zullen later meer references moeten komen omdat deze doorgegeven moeten worden naar `Script` omdat we nu zonder singletons werken.

2024-11-15 18:53 UTC, lonkaars commented on src/crepe/api/BehaviorScript.h
> +BehaviorScript & GameObject::add_component<BehaviorScript>();
Dit heeft trouwens als eindgebruiker het effect dat je de aanroep
```cpp
obj.add_component<BehaviorScript>()
```
kunt gebruiken, zonder dat je zelf een reference naar de component manager vandaan hoeft te toveren om dit te doen (wat het zou zijn zonder deze uitzondering):
```cpp
obj.add_component<BehaviorScript>(component_manager)
```

2024-11-15 18:53 UTC, lonkaars commented on src/crepe/api/Script.h
> +	ComponentManager * component_manager_ref = nullptr;
Ja

2024-11-15 18:54 UTC, lonkaars commented on src/crepe/api/BehaviorScript.cpp
> +}
Hierboven uitgelegd :)

2024-11-15 18:59 UTC, lonkaars commented on src/crepe/api/BehaviorScript.h
> +	bool initialized = false;
`Script` is puur[^*] de interface, en of de `init()` functie al aangeroepen is zie ik als een klein stukje component state. Daarnaast wil ik niet dat de game programmeur met deze variabele kan spelen want dat is niet de bedoeling.

[^*]: Niet echt want script krijgt straks ook een hoop functies om de component manager te prikken omdat dit niet anders kan met dependency injection, maar voor de rest is Script alleen een interface zonder eigen state. De game programmeur mag op deze manier zelf ook nog een member variabele of functie declareren genaamd `initialized` als dat wenselijk is

2024-11-15 19:01 UTC, lonkaars commented on src/crepe/api/Script.h
> +	BehaviorScript * parent_ref = nullptr;
Ik kan er geen reference van maken omdat de constructor van `Script` geen argumenten mag krijgen. Ik heb vanuit `Script` geen directe toegang tot de (niet singleton) `ComponentManager` dus ik heb helaas niks aan enkel een gameobject_id binnen Script.

2024-11-15 19:02 UTC, lonkaars commented on src/crepe/api/Script.h
> +	BehaviorScript * parent_ref = nullptr;
Ik heb op [`loek/audio`](https://github.com/lonkaars/crepe/tree/loek/audio) trouwens nog een utility klasse `OptionalRef` toegevoegd die deze manier van "late" references doorgeven \*iets\* veiliger maakt (haalt mogelijkheid om `delete` aan te roepen weg).

2024-11-15 19:02 UTC, lonkaars commented on src/crepe/api/Config.h
Nee >:(

2024-11-15 19:12 UTC, lonkaars commented on src/crepe/api/Scene.cpp
> +Scene::Scene(ComponentManager & mgr, const std::string & name)
Nee want dit is doorgeven voor dependency injection, en je wil (denk ik) binnen `Scene` componenten kunnen beheren

2024-11-15 19:16 UTC, lonkaars commented on src/crepe/api/SceneManager.hpp
> +	this->scenes.emplace_back(unique_ptr<Scene>(scene));
Ik wil dat `Scene` altijd door `SceneManager` geïnstantieerd wordt. Momenteel kan de gebruiker nog gewoon `Scene` instanties aanmaken, maar mij lijkt dat dit net als components ingeperkt kan worden.

2024-11-15 19:17 UTC, lonkaars commented on src/crepe/api/Transform.h
> +protected:
Member visibility wordt niet overgeërfd

2024-11-15 19:19 UTC, lonkaars commented on src/crepe/api/Transform.h
> +	double scale = 0;
Default waardes zijn juist de standaard. Het definiëren van een standaardwaarde is alleen niet nodig voor klasses/structs die dit zelfstandig doen.

2024-11-16 10:10 UTC, Max-001 commented on src/crepe/api/BehaviorScript.h
> +	~BehaviorScript() = default;
Sorry dat ik hierin zo eigenwijs ben, maar ik denk écht dat deze default (public) destructor hier waardeloos is (en daardoor weg moet).

Als ik je zorgen goed begrijp dan: Twijfel je of het opruimen van `BehaviorScript` wel goed gaat omdat de constructor protected is (en dus alleen `ComponentManager` `BehaviorScript` kan aanmaken). Het klopt dat `std::unique_ptr` `BehaviorScript` moet opruimen, dus de destructor moet public zijn (want `std::unique_ptr` is geen friend). Oftewel: Je twijfelt of de destructor wel/niet public wordt als je dit niet expliciet specificeert.

Ik heb goed nieuws: Er wordt (mits er geen destructor expliciet is aangemaakt) standaard een public default destructor aangemaakt door de compiler.
![image](https://github.com/user-attachments/assets/bdf33c66-0c65-45cc-81dd-1129d4ef5dc4)
https://en.cppreference.com/w/cpp/language/destructor

PS De public default virtual destructor in `Component` is helemaal correct. Daar hoeft niks aan gewijzigd te worden. In het geval van `Component` is het trouwens wél nodig om een default public destructor expliciet te specificeren omdat deze destructor **virtual** moet worden! De destructor van `Component` moet virtual zijn omdat `Component` overgeërfd wordt en de destructors van de overgeërfde klassen aangeroepen moet worden.

Hopelijk is dit te volgen.

2024-11-16 10:20 UTC, Max-001 commented on src/crepe/util/Log.cpp
>  	auto & cfg = Config::get_instance();
Oke, dat klinkt als een goede reden om `Config` als Singleton te houden. Dank voor de uitleg!

2024-11-16 10:23 UTC, Max-001 commented on src/crepe/util/LogColor.h
> +	//! Reset color to default foreground and background color
Helemaal goed!

2024-11-16 10:26 UTC, Max-001 commented on src/example/log.cpp
> +	Log::logf(Log::Level::ERROR, "error");
Ik ben het met je eens. Ik weet niet echt waarom ik dit heb gecomment. Logging moet inderdaad pas gebeuren in de `catch`.

2024-11-16 10:29 UTC, Max-001 commented on src/crepe/Asset.cpp
>  	this->file = std::ifstream(this->src, std::ios::in | std::ios::binary);
Oke, dan ga ik Asset.h en Asset.cpp verder niet nakijken. Het is dan natuurlijk wel belangrijk dat Asset.h en Asset.cpp in zijn geheel wordt nagekeken op loek/audio.

2024-11-16 10:33 UTC, Max-001 commented on src/crepe/Collider.h
> +	using Component::Component;
Ok. Zou je de wijziging dan nog wel even terug willen draaien (ook in Collider.cpp)? Zodat je de master file niet wijzigt. Als het goed is zorgt Jaro ervoor dat deze files correct worden straks.

2024-11-16 12:14 UTC, lonkaars commented on src/crepe/api/BehaviorScript.h
> +	~BehaviorScript() = default;
Ik had dit eerder toegevoegd omdat het voor segmentation faults zorgde, maar ik zie dat het nu prima werkt als ik het weg haal dus dat heb ik gedaan :+1:

2024-11-16 12:24 UTC, lonkaars commented
@Max-001 is het nu goed of zijn er nog belangrijke dingen die aangepast moeten worden? Omdat deze PR al een tijdje open staat denk ik dat het nu "goed genoeg" is en dat andere feedback beter later verwerkt kan worden.

2024-11-16 12:36 UTC, Max-001 commented
> @Max-001 is het nu goed of zijn er nog belangrijke dingen die aangepast moeten worden? Omdat deze PR al een tijdje open staat denk ik dat het nu "goed genoeg" is en dat andere feedback beter later verwerkt kan worden.

Ik ben momenteel bezig met de laatste files/comments checken die ik nog niet bekeken heb. Ik denk dat het zeer binnenkort naar master kan, maar nog ff de rest checken.

2024-11-16 14:18 UTC, Max-001 requested changes
Zoals het er nu naar uitziet worden dit de laatste paar comments voor deze PR. Het ziet er al erg goed uit! Alle comments zijn maar kleine zaken.

Als je de comments verwerkt hebt, hoor ik het graag. Dan zal ik er nog ff overheen scannen en daarna zal ik een Approve geven.

2024-11-16 14:18 UTC, Max-001 commented on src/crepe/api/Script.h
> +	friend class BehaviorScript;
Ik denk dat het protected maken van de constructor geen zin heeft. Uiteindelijk gaat de gebruiker (game programmeur) namelijk overerven van Script en zodra dat gebeurd, geldt de visibility van de constructor die de gebruiker heeft gemaakt (en dat zal waarschijnlijk gewoon een public constructor zijn).
Ik denk dus dat deze default constructor (inclusief de friend `BehaviorScript`) weg kan.

2024-11-16 14:18 UTC, Max-001 commented on src/crepe/ComponentManager.h
> +	// TODO: doxygen
Je zegt het zelf al :)

2024-11-16 14:18 UTC, Max-001 commented on src/crepe/ComponentManager.h
> +	std::forward_list<std::unique_ptr<GameObject>> objects;
Hier mist nog Doxygen

2024-11-16 14:18 UTC, Max-001 commented on src/crepe/ComponentManager.h
>  	 * \brief Delete all components of a specific type and id
Dit is niet voor nu, maar voor later: Misschien is het een goed idee om alle `delete_components_...` methodes protected/private te maken en de `SceneManager` als friend toe te voegen (zodat alleen de `SceneManager` components kan deleten).

2024-11-16 14:24 UTC, Max-001 commented on src/crepe/ComponentManager.cpp
> +GameObject ComponentManager::new_object(const string & name, const string & tag,
Een `Script` hoort natuurlijk bij een `game_object_id`, dus als je component(s) opvraagt in een script, verwacht je ook components terug van dat dat `game_object_id`. Ik denk dat je inderdaad gelijk hebt dat het (voor nu) niet mogelijk hoeft te zijn om components van (andere) `game_object_id` op hoeft te kunnen vragen (ook niet d.m.v. de naam).

2024-11-16 14:26 UTC, Max-001 commented on src/crepe/api/SceneManager.hpp
> +	this->scenes.emplace_back(unique_ptr<Scene>(scene));
Onee, dat gaat helemaal niet denk ik. Want de game programmeur gaat straks zelf overerven van `Scene` en dan geldt de visibility van de constructor van de overgeërfde klasse.
Maar voor nu is het wel oke denk ik.

2024-11-16 14:59 UTC, lonkaars commented on src/crepe/api/Transform.h
> +	double scale = 0;
Het definiëren van standaardwaardes voor variabelen met types die wel zelfstandig initialiseren (zoals `std::string` of `Vector2`) is inderdaad niet nodig, maar wel gewoon toegestaan. Deze regel is in de code standaard gezet omdat ongeïnitialiseerde variabelen voor rare bugs kunnen zorgen.

In dit geval is het "veiliger" dan nodig, maar het maakt de code ook niet trager, dus ik zie het voordeel van weghalen hier niet.

2024-11-16 15:00 UTC, lonkaars commented on src/crepe/api/LoopManager.h
> +	void load_system();
Dit is code van Wouter

2024-11-16 15:07 UTC, lonkaars commented on src/crepe/api/LoopManager.h
> +	ComponentManager & get_component_manager();
Omdat de loop manager zelf geen singleton is en zelf verantwoordelijk is voor alle managers/systems instantiëren en doorgeven aan elkaar kan deze functie inderdaad gewoon weg. Ik denk wel dat het een goed idee is om LoopManager te hernoemen naar `Entrypoint` of `Main` oid.

2024-11-16 15:14 UTC, lonkaars commented on src/crepe/api/LoopManager.hpp
> +	System * system = new T(this->component_manager);
In de unit tests wil ik wel systeem-klassen aan kunnen maken. Momenteel geef ik mezelf toegang tot alles in de unit tests met deze gore truc:
```cpp
#include <gtest/gtest.h>

#define private public
#define protected public

// hier crepe headers includen
```
Ik vind dit alleen lelijk, maar het werkt wel. Ik ga er trouwens niet van uit dat de game programmeur überhaupt de systeem headers krijgt, want je hebt geen directe toegang nodig tot de systemen om een game te implementeren. Ik laat nu alle systemen een public constructor hebben, maar als we daar ooit van af stappen zal de loopmanager in ieder geval blijven werken.

2024-11-16 15:17 UTC, lonkaars commented on src/crepe/api/BehaviorScript.h
> +	bool initialized = false;
Ik kan inderdaad heel slecht nadenken haha

2024-11-16 15:24 UTC, lonkaars commented on src/crepe/api/Script.h
> +	T & get_component() const;
Dit is eigenlijk alleen handig voor `Transform` en `Metadata`, waar het logisch is dat er altijd exact 1 is.

2024-11-16 16:45 UTC, Max-001 commented on src/crepe/api/Transform.h
> +	double scale = 0;
Oke, daar valt ook iets voor te zeggen. Helemaal goed zo.

2024-11-16 16:55 UTC, Max-001 commented on src/crepe/api/LoopManager.hpp
> +	System * system = new T(this->component_manager);
Hahah, dat is inderdaad een gore truc, maar wel slim.
Moeten we de constructor in System.h dan niet wel protected maken (met als friend `LoopManager`)?

2024-11-16 17:00 UTC, Max-001 commented on src/crepe/api/Script.h
> +	T & get_component() const;
Is het dan een goed idee om een `static_assert` hier toe te voegen die checkt of het type `Transform` óf `Metadata` is?

2024-11-16 17:07 UTC, Max-001 commented on src/crepe/api/LoopManager.h
> +	ComponentManager & get_component_manager();
Een andere naam kan inderdaad geen kwaad. Maar liever niet in deze PR :)

2024-11-16 17:13 UTC, Max-001 commented on src/crepe/api/Script.h
> +	friend class BehaviorScript;
Helder. Dan laten we dit gewoon zo.

2024-11-16 18:22 UTC, Max-001 requested changes
Als het goed is de aller laatste (kleine) comment voor de PR.
Er staan nog twee comments open van de vorige review sessie (zie LoopManager.hpp en Script.h).

2024-11-16 19:42 UTC, lonkaars commented on src/crepe/ComponentManager.h
> +	friend class SceneManager;
Ik vind het raar als `SceneManager` gebruikt wordt om componenten te *verwijderen* wanneer we `GameObject` gebruiken om componenten te *maken*. Uiteindelijk wordt alles (qua geheugenbeheer) door `ComponentManager` beheerd, maar ik denk wel dat het netjes zou zijn als het verwijderen van de `GameObject` instantie die `ComponentManager::new_object` teruggeeft er automatisch voor zorgt dat de componenten ook verwijderd worden.

Omdat we nog geen mini-game / testapplicatie gemaakt hebben wil ik dit graag uitstellen omdat ik totaal geen verdere onderbouwing kan geven dan "dit is hoe ik het in gedachten had".

2024-11-16 19:44 UTC, lonkaars commented on src/crepe/api/LoopManager.hpp
> +	System * system = new T(this->component_manager);
Ik laat het nu zoals het is omdat de game programmeur straks de system headers niet eens kan `#include`en, dus het eigenlijk niet veel verschil maakt (naast de unit tests allemaal 2 regels groter maken).

2024-11-16 19:48 UTC, Max-001 commented on src/crepe/ComponentManager.h
> +	friend class SceneManager;
Prima. Helder

2024-11-16 19:51 UTC, Max-001 commented on src/crepe/ComponentManager.h
> +	friend class SceneManager;
Ik denk trouwens wel dat het veel lastiger is om het deleten van alle components aan GameObjects over te laten. Maar dat is iets voor een latere vragenronde :)

2024-11-16 19:52 UTC, Max-001 commented on src/crepe/api/LoopManager.hpp
> +	System * system = new T(this->component_manager);
Prima

2024-11-16 20:37 UTC, merged