Wouter/events
lonkaars/crepe pull request #34
Opened 2024-11-13 14:45 UTC by Wboerenkamps

2024-11-13 17:41 UTC, Max-001 commented on .vscode/launch.json
Zou je deze file weg willen halen?

2024-11-13 17:42 UTC, Max-001 commented on .vscode/tasks.json
Zou je deze file ook weg willen halen?

PS Dit is geen review wat ik nu doe, het valt me toevallig op.

2024-11-14 18:47 UTC, JaroWMR commented
Kun je de lib weg halen?

2024-11-14 18:57 UTC, JaroWMR commented
en 1 event.h die niet gebruikt word

2024-11-14 19:24 UTC, JaroWMR requested changes

2024-11-14 19:28 UTC, Wboerenkamps commented on src/crepe/api/EventManager.cpp
ik denk niet dat dit echt gaat om magic numbers aangezien het de index is van de tuple

2024-11-14 20:08 UTC, JaroWMR commented on src/crepe/api/EventManager.cpp
wat je kunt toevogen is geen must is een enum met pointer,channel,event_type; en dan die vervangen. maar omdat het ervoor staat is het ook al wel duidelijk

2024-11-14 20:40 UTC, Wboerenkamps commented on src/crepe/api/EventHandler.h
de interface klasse heb ik nodig zodat eventWrappers van ieder typen opgeslagen kunnen worden

2024-11-17 20:41 UTC, JaroWMR requested changes

2024-11-17 20:41 UTC, JaroWMR commented on lib/sdl2
remove this folder from pr

2024-11-17 20:41 UTC, JaroWMR commented on mwe/events/include/event.h
remove this form pr

2024-11-17 20:41 UTC, JaroWMR commented on src/crepe/api/IKeyListener.cpp
fix rule of 5

2024-11-17 20:41 UTC, JaroWMR commented on src/crepe/api/IMouseListener.cpp
de tabs staan vreemd in deze file is dit github?

2024-11-17 20:41 UTC, JaroWMR commented on src/crepe/api/IMouseListener.h
is er een rede voor:
* \brief Copy constructor (deleted).
     */
	IMouseListener(const IMouseListener &) = delete;

	/**
     * \brief Copy assignment operator (deleted).
     */
	IMouseListener & operator=(const IMouseListener &) = delete;

	/**
     * \brief Move constructor (deleted).
     */
	IMouseListener(IMouseListener &&) = delete;

	/**
     * \brief Move assignment operator (deleted).
     */
	IMouseListener & operator=(IMouseListener &&) = delete;
	
	en default destuctors hoeve geen comments

2024-11-18 14:28 UTC, Wboerenkamps commented on src/crepe/api/IMouseListener.cpp
ik denk dat het aan github ligt want in mijn code is het wel normaal

2024-11-18 15:52 UTC, JaroWMR commented on mwe/events/include/event.h
is prima ik dan hebben andere er ook geen last meer van

2024-11-18 15:53 UTC, Wboerenkamps commented on mwe/events/include/event.h
ik had hem toch nog weggehaald dus probleem opgelost

2024-11-18 16:00 UTC, JaroWMR requested changes

2024-11-18 16:00 UTC, JaroWMR commented on src/crepe/api/IKeyListener.h
Move Assignment Operator: Missing

2024-11-19 19:16 UTC, lonkaars requested changes
1. `git checkout master -- lib/sdl2 lib/sdl_image lib/sdl_ttf`
2. `make format`
3. de rest

:)

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/IMouseListener.cpp
> +	mouse_click_handler
Idem met `this->`

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/IMouseListener.h
> +	IMouseListener && operator=(const IMouseListener &&) = delete;
Move assignment operator returnt normale reference (`&`) geen rvalue reference (`&&`)

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/IMouseListener.h
> +	IMouseListener(int channel);
Ook hier kan `int channel = 0` staan ipv 2 constructors

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/IMouseListener.h
> +	virtual bool on_mouse_clicked(const MouseClickEvent & event) = 0;
Ik zie nu trouwens ook dat al deze functies pure virtual zijn inplaats van virtual met een lege implementatie, is dit ook bewust? Waarom zou je een interface willen die je forceert *alle* handlers te implementeren?

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/IMouseListener.h
> +	void set_channel(int channel);
Ook hier mag deze functie helemaal weg

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/KeyCodes.h
> +enum class MouseButton {
Dit is niet hoe Doxygen werkt, dit kan gewoon:

```cpp
//! Enumeration for mouse button inputs, including standard and extended buttons.
enum class MouseButton {
```
zijn

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/KeyCodes.h
> +	NONE = 0,
Voor enum constantes kun je ook de volgende Doxygen notatie gebruiken:

```cpp
NONE = 0, //< No mouse button input.
LEFT_MOUSE = 1, //< Left mouse button.
RIGHT_MOUSE = 2, //< Right mouse button.
MIDDLE_MOUSE = 3, //< Middle mouse button (scroll wheel press).
X1_MOUSE = 4, //< First extended mouse button.
X2_MOUSE = 5, //< Second extended mouse button.
SCROLL_UP = 6, //< Scroll wheel upward movement.
SCROLL_DOWN = 7 //< Scroll wheel downward movement.
```

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/KeyCodes.h
> +	SCROLL_DOWN = 7
Hier moet een komma (einde van lijst, zie contributing.md)

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/KeyCodes.h
> +enum class Keycode : int {
Enum klasse met een base type? Weet je het zeker?

2024-11-19 19:16 UTC, lonkaars commented on src/crepe/api/KeyCodes.h
> +	//! Function keys (F1-F25).
Deze comment staat nu alleen bij `F1`, waarschijnlijk zoek je

```cpp
	/**
	 * \name Function keys (F1-F25).
	 * \{
	 */
	F1 = 290,
	F2 = 291,
	F3 = 292,
	F4 = 293,
	F5 = 294,
	F6 = 295,
	F7 = 296,
	F8 = 297,
	F9 = 298,
	F10 = 299,
	F11 = 300,
	F12 = 301,
	F13 = 302,
	F14 = 303,
	F15 = 304,
	F16 = 305,
	F17 = 306,
	F18 = 307,
	F19 = 308,
	F20 = 309,
	F21 = 310,
	F22 = 311,
	F23 = 312,
	F24 = 313,
	F25 = 314,
	/// \}
```

om ze als groep te documenteren in Doxygen

2024-11-20 08:15 UTC, Wboerenkamps commented on src/crepe/api/Event.h
het triggeren is af maar staat in de inputsystem branch. Is het niet duidelijker om alle events bij elkaar te hebben staan in plaats van verspreid door verschillende bestanden waar ze getriggered worden?

2024-11-20 08:23 UTC, Wboerenkamps commented on src/crepe/api/Event.h
> +class KeyReleaseEvent : public Event {
Als ik bijvoorbeeld een MouseEvent aanmaak met daarin mouse_x en mouse_y dan werkt deze aanroep niet meer:  ```MouseClickEvent{
				.mouse_x = 100,
				.mouse_y = 100,
				.button = MouseButton::LEFT_MOUSE,
			},```

2024-11-20 08:33 UTC, Wboerenkamps commented on src/crepe/api/EventHandler.h
> +	virtual std::string get_type() const = 0;
ja de naam is een beetje verwarrend maar deze variable stored ```handler.target_type().name()``` wat een unique naam is voor de callback met deze waarde unsubscribe ik de callback ook.

2024-11-20 10:28 UTC, Wboerenkamps commented on src/crepe/api/IKeyListener.h
> +	int channel = 0;
dan kan de channel gebruikt worden om te unsubscriben en makkelijk gewisseld worden door setChannel()

2024-11-20 10:29 UTC, Wboerenkamps commented on src/crepe/api/IKeyListener.h
> +	bool active = true;
wat bedoel je met een normale event subscibe api?

2024-11-20 10:29 UTC, Wboerenkamps commented on src/crepe/api/EventManager.h
> +	void unsubscribe(const EventHandler<EventType> &, int channel = 0);
omdat het op het moment met de twee lijsten werken maar is waarschijnlijk niet meer nodig als ik er 1 lijst van heb gemaakt

2024-11-20 10:35 UTC, Wboerenkamps commented on src/crepe/api/IKeyListener.h
> +	bool active = true;
ik denk wel dat deze api toegevoegde waarde heeft om makkelijk een callback toe te voegen aan een behavior script zonder expliciet subscribe en unsubscribe te callen

2024-11-20 13:27 UTC, lonkaars commented on src/crepe/api/Event.h
> +class KeyReleaseEvent : public Event {
Oh ja dat klopt, laat maar

2024-11-20 13:31 UTC, lonkaars commented on src/crepe/api/Event.h
Ik vind het persoonlijk juist duidelijker als ze staan bij de code die de waardes invult inplaats van allemaal in één groot bestand. Misschien iets om te discussiëren in de groep?

2024-11-20 13:36 UTC, lonkaars commented on src/crepe/api/EventManager.cpp
> +		if (channel) {
Liever een
```cpp
#include <cstdint>
typedef uint32_t event_channel_t;
```
in EventManager.h en een
```cpp
public:
  static constexpr const event_channel_t CHANNEL_BROADCAST = -1;
```
in de klassedefinitie van EventManager

2024-11-20 13:37 UTC, lonkaars commented on src/crepe/api/EventManager.cpp
> +		if (channel) {
En dan overal waar je `int channel = 0` hebt staan vervangen met `event_channel_t channel = EventManager::CHANNEL_BROADCAST`

2024-11-20 13:38 UTC, lonkaars commented on src/crepe/api/EventHandler.h
> +	virtual std::string get_type() const = 0;
Waarom hebben de callbacks namen nodig?

2024-11-20 13:42 UTC, lonkaars commented on src/crepe/api/IKeyListener.h
> +	int channel = 0;
De `set_channel` functie mag wat mij betreft compleet weg omdat deze nergens nodig is. Ik heb ook liever dat je überhaupt geen channel en eventhandler reference nodig hebt om te unsubscriben. (zie [deze comment](https://github.com/lonkaars/crepe/pull/34/files#r1848865745))

2024-11-20 13:46 UTC, lonkaars commented on src/crepe/api/IKeyListener.h
> +	bool active = true;
Ik moet in `Script` toch al een wrapper toevoegen om `EventManager::subscribe` die de callback functie van de gebruiker niet uitvoert als het component niet actief is. Met deze API trek je de event handling interface compleet los van ECS, dus is het niet langer mogelijk om Component::active te bekijken, wat componenten die deze API gebruiken compleet stuk zou kunnen maken. Met de normale event subscribe API bedoel ik
```cpp
EventManager::get_instance().subscribe<Type>(bla bla bla);
```

2024-11-20 15:16 UTC, Wboerenkamps commented on src/crepe/api/EventManager.h
> +		subscribers_by_event_id;
ik voeg ook meteen priority erbij toe anders als je de events stopt door true te returnen weet je nooit welke events wel of niet worden uitgevoerd

2024-11-20 15:22 UTC, lonkaars commented on src/crepe/api/EventManager.h
> +		subscribers_by_event_id;
Priority voegt weer onnodige complexiteit toe dus mag wat mij betreft weg. Voor de rest ziet dit er prima uit, het enige dat ik niet begrijp is dat de subscribers in een unordered map staan. Is het nu niet meer mogelijk om meerdere subscribers op dezelfde event soort te hebben, of verwijst die type_index naar de typeid van de callback functie?

2024-11-20 15:23 UTC, lonkaars commented on src/crepe/api/EventManager.h
> +		subscribers_by_event_id;
En `channel = 0` moet dus vervangen worden met `CHANNEL_BROADCAST` (of hoe je de constante genoemd hebt)

2024-11-20 21:03 UTC, lonkaars commented
Deze PR is gemerged maar GitHub heeft crack op?

2024-11-20 21:03 UTC, closed without merging