Niels/sorting rendering
lonkaars/crepe pull request #38
Opened 2024-11-18 14:11 UTC by heavydemon21

2024-11-18 16:02 UTC, lonkaars requested changes
Naast de comments heb ik ook graag dat je nog `make format` over alles heen gooit (doe dit wel aub in een losse commit)

2024-11-18 16:02 UTC, lonkaars commented on src/crepe/system/RenderSystem.cpp
> +	if (objs.empty()) return {};
Deze check is overbodig want er wordt sowieso al een lege vector gemaakt in dit geval (of dit `{}` of `sorted_objs` is maakt niet uit), en `std::sort` doet niks als `begin()` en `end()` de zelfde iterator zijn.

2024-11-18 17:21 UTC, lonkaars commented on src/crepe/system/RenderSystem.h
>  	 * \todo Include color handling for sprites.
(Zie #39)

2024-11-18 20:03 UTC, heavydemon21 commented on src/crepe/system/RenderSystem.cpp
>  	SDLContext & render = SDLContext::get_instance();
das wel een probleem want `texture, rendersystem, animatorsystem, looptimer, waarschijnlik loopmanager(events) gebruiken allemaal delen van de sdlcontext`

2024-11-18 20:04 UTC, heavydemon21 commented on src/example/rendering.cpp
is het goed als ik deze week alle PR's erin hebt en dan in een keer een alle unit tests in een PR

2024-11-18 20:06 UTC, heavydemon21 commented on src/crepe/system/RenderSystem.cpp
> +	auto sorted_sprites = this->sort(sprites);
Jaro gaf aan dat het wel mag op een andere PR#31

2024-11-19 08:34 UTC, lonkaars commented on src/crepe/system/RenderSystem.cpp
> +	auto sorted_sprites = this->sort(sprites);
Ik neem aan dat je [deze](https://github.com/lonkaars/crepe/pull/31#discussion_r1842219417) comment bedoelt? In de code standaard staat dat `auto` alleen toegestaan is in de volgende gevallen:
- Bij range-based for loops (niet het geval hier)
- Wanneer je een singleton reference opvraagt (ook niet het geval)
- Bij template methods waar het return type al in de functieaanroep staat

  In dit geval staat `Sprite` wel in de functieaanroep, maar is het nog niet duidelijk dat deze nog in een `vector<reference_wrapper<` zit.

Omdat dit een type is die regelmatig gebruikt wordt denk ik dat het handig is om een `ReferenceList` type toe te voegen aan src/crepe/types.h:
```cpp
template <typename T>
using ReferenceList = std::vector<std::reference_wrapper<T>>;
```

2024-11-19 08:36 UTC, heavydemon21 commented on src/crepe/system/RenderSystem.cpp
> +	auto sorted_sprites = this->sort(sprites);
fine, ik zal het aanpassen

2024-11-19 08:36 UTC, lonkaars commented on src/example/rendering.cpp
Is er een reden waarom het niet direct in deze PR kan? Unit tests zelf worden niet op code standaard gecontroleerd dus ik zie liever meteen bij deze pull request dat jouw code functioneel ook in orde is.

2024-11-19 08:52 UTC, lonkaars commented on src/crepe/system/RenderSystem.cpp
>  		SDLContext::get_instance().camera(cam);
Sla `SDLContext` op als een reference member van RenderSystem, dit maakt het later makkelijker met refactoren als `SDLContext` niet langer een singleton is:

RenderSystem.h (in `class RenderSystem`)
```cpp
private:
	SDLContext & context = SDLContext::get_instance();
```

2024-11-19 09:00 UTC, lonkaars commented
Ik mag van GitHub geen comments achterlaten op niet-PR code, dus hier nog wat dingen die ik zie:
- src/crepe/system/RenderSystem.h:
  - `RenderSystem::clear_screen` en `RenderSystem::present_screen` zijn `const` gemarkeerd, terwijl deze bijwerkingen hebben
  - In de Doxygen beschrijving van `class RenderSystem` staat *"It functions as a singleton"*, dit is niet zo, en hoort ook niet in deze beschrijving te staan (Systeem beschrijving bevat wat het systeem regelt en voor welke concrete `Component`-klassen deze zorgt)
  - De includes voor `Sprite` en `Camera` kunnen beide vervangen worden door een forward declaration
- src/crepe/api/Sprite.h:
  - `#include "Component.h"` moet eigenlijk `"../Component.h"` zijn

2024-11-19 10:50 UTC, heavydemon21 commented on src/crepe/system/RenderSystem.cpp
>  	SDLContext & render = SDLContext::get_instance();
Loopmanager moet uiteindelijk de sdl events aanroepen en dat doe je via sdlcontext.
animatorsystem gebruikt voor nu de sdl ticks om een animatie te updaten.
looptimer gebruikt ook de ticks.

2024-11-20 10:46 UTC, heavydemon21 commented on src/crepe/system/RenderSystem.cpp
>  	SDLContext & render = SDLContext::get_instance();
@lonkaars mag ik dit dan oplossen bij een van de volgende PR's zodat ik dan een oplossing hiervoor sinds wouters gedeelte er ook van afhankelijk is.

ik denk namelijk dat animator system ervan af kan want die kan veradert worden door de loopmanager fps(maybe).
looptimer gaat met de latere aanpassingen er ook vanaf.

dan is nog alleen rendersystem en texture en alleen nog maar voor loopmanager de events.

natuurlijk doe ik wel de aanpassing in rendersysyem hiervoor die je had vermeld

2024-11-20 12:22 UTC, lonkaars commented on src/example/rendering.cpp
Nu je unit tests hebt mag deze ook weg

2024-11-20 12:33 UTC, heavydemon21 commented on src/crepe/system/RenderSystem.cpp
> +		this->context.camera(cam);
gedaan in een andere branch

2024-11-20 12:37 UTC, heavydemon21 commented on src/example/rendering.cpp
mag dit er in blijven omdat ik dan nog visueel kan testen

2024-11-20 12:56 UTC, lonkaars approved these changes

2024-11-20 12:57 UTC, merged