Niels/remove singleton
lonkaars/crepe pull request #70
Opened 2024-12-09 14:37 UTC by heavydemon21

Has still the issue that if an Animator component is added the aspect ratio of the cropped image is not correct anymore.

2024-12-10 12:26 UTC, Wboerenkamps commented on src/crepe/api/Sprite.h
> +	const Asset source;
aangezien je het als een reference binnenkrijgt moet dit niet ook een reference zijn?

2024-12-10 14:48 UTC, heavydemon21 commented on src/crepe/api/Sprite.h
> +	const Asset source;
mag niet sprite houdt hem vast kijk bij audiosource

2024-12-11 14:29 UTC, lonkaars commented on src/crepe/api/Config.h
> +		Log::Level level = Log::Level::TRACE;
Dit moet teruggezet worden

2024-12-11 14:29 UTC, lonkaars commented on src/crepe/api/Animator.h
> +	const uvec2 max_cell_size;
Deze naam en de documentatie beschrijving zijn onduidelijk, zelfde geldt voor constructor parameter

2024-12-11 14:31 UTC, lonkaars commented on src/crepe/api/LoopManager.h
> +	ResourceManager res_man{mediator};
Geen namen afkorten (en dit is als het goed is al opgelosd op master?)

2024-12-11 14:32 UTC, lonkaars commented on src/crepe/api/LoopTimer.h
> +class Mediator;
Deze declaratie kan weg

2024-12-11 14:34 UTC, lonkaars commented on src/crepe/facade/SDLContext.cpp
> +	mediator.sdl_context = *this;
Ik zou deze wel helemaal aan het einde van de constructor doen want je gooit mogelijk exceptions in je constructor

2024-12-11 14:36 UTC, lonkaars commented on src/crepe/facade/SDLContext.h
> +class SDLContext : public Manager {
Is SDLContext een manager nu?

2024-12-11 14:38 UTC, lonkaars commented on src/crepe/facade/SDLContext.h
> +	SDL_Rect mask = {};
Ben geen enorme fan van deze oplossing met `get_src_rect`. Kun je de `get_src_rect` gewoon helemaal weg doen omdat hij toch alleen op één plaats aangeroepen wordt? Dan kun je deze member meteen weer weghalen en gewoon een stackvariabele laten.

2024-12-11 14:39 UTC, lonkaars commented on src/crepe/facade/Texture.h
> +// FIXME: this header can't be included because this is an API header, and SDL2 development
Deze fixme comment kan weg omdat Texture nu niet langer vanuit de API toegankelijk is

2024-12-11 14:39 UTC, lonkaars commented on src/crepe/manager/EventManager.cpp
Dit bestand kan weer gerevert worden omdat het niks met deze PR te maken heeft

2024-12-11 14:40 UTC, lonkaars commented on src/crepe/manager/SceneManager.cpp
Deze mag ook gerevert worden

2024-12-11 14:41 UTC, lonkaars commented on src/test/CMakeLists.txt
Ook revert :upside_down_face:

2024-12-11 14:42 UTC, lonkaars commented on src/test/Profiling.cpp
Ook revert (met uitzondering van de `Texture` -> `Asset` aanpassingen). Om de `DISABLED_*` tests te draaien kun je `test_main --gtest_also_run_disabled_tests` draaien.

2024-12-11 15:13 UTC, heavydemon21 commented on src/test/RenderSystemTest.cpp
>  	// no texture img
dat was in het begin neit zo

2024-12-11 15:22 UTC, lonkaars requested changes
Als de unit tests compileren en allemaal (ook met `--gtest_also_run_disabled_tests`) passen zal ik 'm mergen

2024-12-11 15:22 UTC, lonkaars commented on src/test/Profiling.cpp
> +			auto img = Texture("asset/texture/square.png");
Deze test is nu weer stuk. `Texture` moet denk ik nog vervangen worden met `Asset`.

2024-12-11 15:48 UTC, merged