fps hotfix + regression test
lonkaars/crepe pull request #76
Opened 2024-12-12 18:49 UTC by Wboerenkamps

get_fps fix + test

2024-12-12 18:53 UTC, JaroWMR requested changes
Functioneel niet getest een include staat niet op de juiste plek.

2024-12-12 18:53 UTC, JaroWMR commented on src/crepe/manager/LoopTimerManager.cpp
> +#include "../util/Log.h"
de include volgorde klopt niet

2024-12-12 18:58 UTC, JaroWMR commented
test_main succeed en de test zelf ziet er goed uit. @heavydemon21 Moet ook nog reviewen want dit kwam vanaf hem.

2024-12-12 18:59 UTC, Wboerenkamps commented on src/crepe/manager/LoopTimerManager.cpp
> +#include "../util/Log.h"
die kwam van de merge

2024-12-12 18:59 UTC, Wboerenkamps commented on src/crepe/manager/LoopTimerManager.cpp
> +#include "../util/Log.h"
ik pas hem meteen aan

2024-12-13 12:54 UTC, Max-001 reviewed
![image](https://github.com/user-attachments/assets/709990ab-526a-41df-9a1e-470f173d994d)
De test lijkt iets te specifiek/niet rekening te houden met afrond fouten. Graag dit ff fixen, daarna is het goed.

2024-12-13 16:01 UTC, Max-001 approved these changes

2024-12-13 16:55 UTC, JaroWMR approved these changes

2024-12-13 16:56 UTC, merged