Jaro/collision system handeling
lonkaars/crepe pull request #85
Opened 2024-12-16 20:29 UTC by JaroWMR

DEPENDENT ON #83 AND #74

2024-12-17 16:22 UTC, Max-001 commented
Ik ben klaar met het functioneel testen van Sprite renderen, dat ziet er allemaal goed uit!

Bij de ParticleEmitter mis ik nog wel een paar kleine functionaliteiten, ik zal deze hieronder opsommen.
Ik heb de volgende testcode gemaakt:
![image](https://github.com/user-attachments/assets/60239d00-d0df-4cf5-99ab-ffc06824c64a)
1. Het is mij opgevallen dat de `position_offset` van de `Sprite` (op regel 233) niets doet zodra de Sprite wordt gekoppeld aan een ParticleEmitter. Ik zou verwachten dat deze offset gewoon de offset t.o.v. ParticleEmitter z'n `offset` + `Transform::position` zou zijn.
2. Het is mij opgevallen dat de `rotation` van het GameObject (dus van de Transform) ook niets doet. Ik zou verwachten dat hiermee de gehele ParticleEmitter zou worden gedraaid (inclusief de Sprites natuurlijk, net zoals gebeurt bij een individuele Sprite).

Ik weet niet of het lukt om ook nog de collisions na te kijken vandaag, dat wordt waarschijnlijk het eerste wat ik morgenochtend ga doen.

2024-12-17 19:58 UTC, JaroWMR commented
NORMAAL:

Ik zal even beschrijven wat je verwacht tussen de bodytypes (collision types):

Dynamic handling = beide objecten verplaatsen half terug.
Static handeling = Dynamic object verplaats volledig terug.
Script oncollision = voor beide objecten worden de script aangeroepen

Dynamic-Dynamic (Dynamic collision handling + Script oncollision) 
Dynamic-Kinematic (Static handeling (met kinematic bool)  + Script oncollision)
Dyanmic-Static (Static handeling + Script oncollision)

Kinematic-Kinematic  (geen handeling +Script oncollision )
Kinematic-Static  (geen handeling + Script oncollision )

Static-Static (geen handeling +geen script)

In game.cpp is het eenvoudig om te switchen tussen de rigidbody types.
Kijk even in de scripts hoe je verplaatst.

Voor ieder van de bovenstaande collision types moet je beide objecten getest hebben.
Dus de eerste keer is object 1 dynamic en object 2 static.
Daarna object 1 static en object 2 dynamic.

Dit moet je testen IVM hoe het systeem werkt als user zou je hier geen verschil in merken.
De script print als er collision is met log en de huidige velocity wordt ook geprint.


BOUNCE:
Voor bounce geld precies het bovenstaande alleen de objecten inverteren hun velocity op de juiste manier.
Dynamic handleing past de elasticity toe op beide objecten van hun eigen rigidbody (te testen door 1 geen bounce te geven)
Static bounced alleen het object dat dynamic is.

2024-12-17 21:17 UTC, lonkaars requested changes
Alle `*_collision_handler`-functies die een `CollisionInfo &` nemen moeten
eigenlijk een `const CollisionInfo &` nemen (references *binnen* een const
reference zijn *niet* const). Dit is de enige code standaard aanpassing die
gemaakt moet worden naast de comments.

Ik heb ook nog een paar suggesties om de code van het hele `CollisionSystem` een
stuk leesbaarder te maken:
- De `CollisionInfo` struct op de volgende manier definiëren:
  ```cpp
  struct ColliderInfo {
    Collider & collider;
    Transform & transform;
    Rigidbody & rigidbody;
    Metadata & metadata;
  };

  struct CollisionInfo {
    ColliderInfo our;
    ColliderInfo their;
    vec2 resolution;
    Direction resolution_direction;

    CollisionInfo operator - () const;
  };
  ```
  Hierdoor kun je makkelijk de inverse `ColliderInfo` berekenen door gewoon
  `-info` oid te schrijven. De implementatie van deze functie is dan
  ```cpp
  CollisionSystem::CollisionInfo CollisionSystem::CollisionInfo::operator-() const {
    return {
      .our = this->their,
        .their = this->our,
        .resolution = -this->resolution,
        .resolution_direction = this->resolution_direction,
    };
  }
  ```
  `CollisionSystem::call_collision_events` kan er dan gewoon zo uit zien:
  ```cpp
  void CollisionSystem::call_collision_events(const CollisionInfo & info) {
    EventManager & emgr = this->mediator.event_manager;
    emgr.trigger_event(CollisionEvent{info}, info.our.metadata.game_object_id);
    emgr.trigger_event(CollisionEvent{-info}, info.their.metadata.game_object_id);
  }
  ```
- Op een aantal plekken probeer je berekeningen te 'besparen' door met
  if-statements te kijken of een vector bijvoorbeeld met 0 wordt
  vermenigvuldigd. Ik zou het fijner vinden als je deze allemaal weg haalt en de
  berekeningen gewoon 'blind' toepast, bijv.
  ```cpp
  void CollisionSystem::static_collision_handler(const CollisionInfo & info) {
    info.our.transform.position += info.resolution;

    switch (info.resolution_direction) {
      case Direction::BOTH:
        info.our.rigidbody.data.linear_velocity = -info.our.rigidbody.data.linear_velocity * info.our.rigidbody.data.elastisity_coefficient;
        break;
      case Direction::Y_DIRECTION:
        info.our.rigidbody.data.linear_velocity.y = -info.our.rigidbody.data.linear_velocity.y * info.our.rigidbody.data.elastisity_coefficient;
        break;
      case Direction::X_DIRECTION:
        info.our.rigidbody.data.linear_velocity.x = -info.our.rigidbody.data.linear_velocity.x * info.our.rigidbody.data.elastisity_coefficient;
        break;
      case Direction::NONE:
        break;
    }
  }
  ```
- De branching in `CollisionSystem::determine_collision_handler` is ontzettend
  lastig te volgen. Ik raad aan dat je de aanroep naar
  `CollisionSystem::call_collision_events` verplaats buiten deze functie, en
  erna uit voert in `CollisionSystem::collision_handler_request`. Ik zou
  `determine_collision_handler` ook hernoemen naar `any_collision_handler` omdat
  dat dichter in de buurt komt van wat deze functie daadwerkelijk doet. Hierdoor
  zou de onderkant `CollisionSystem::collision_handler_request` functie er zo
  uit zien:
  ```cpp
  void CollisionSystem::collision_handler_request(CollisionInternal & our_data, CollisionInternal & their_data) {
    // .....

    // collision info
    CollisionInfo collision_info {
      .our = {
        .collider = our_collider,
        .transform = our_data.transform,
        .rigidbody = our_data.rigidbody,
        .metadata = our_metadata,
      },
        .their = {
          .collider = their_collider,
          .transform = their_data.transform,
          .rigidbody = their_data.rigidbody,
          .metadata = their_metadata,
        },
        .resolution = resolution_data.first,
        .resolution_direction = resolution_data.second,
    };

    this->any_collision_handler(collision_info);
    this->call_collision_events(collision_info);
  }
  ```
- Ik zie volgensmij ook een patroon waarbij `CollisionSystem::Direction`
  berekeningen 'maskt' op een bepaalde as. Bij alle functies waarin deze wordt
  gebruikt zijn ontzettend veel herhaalde berekeningen binnen geneste
  if-statements die de code onleesbaar maken. Dit zou je bijvoorbeeld op kunnen
  lossen door:
  - `Direction` compleet weg te halen en te vervangen met een `vec2` waarbij de
    x/y as altijd exact 1 of 0 is; De berekeningen blindelings altijd uitvoeren
    op een tijdelijke vec2; Deze twee vectoren vermenigvuldigen en optellen bij
    de resultaat-vector.
  - `Direction` vervangen met een bitmask enum; De berekeningen los uitvoeren
    per as, afhankelijk van of de enum bits ingesteld zijn.

    Hier hou je nog steeds duplicatie overhouden ivm de x/y assen, maar hier kun
    je eventueel om heen door helper lambda functies te maken die per as de
    berekening uitvoeren.

Functioneel werkt de huidige code, dus ik vind het prima om te mergen zoals het
nu is, maar deze aanpassingen zouden wel mooiere code opleveren denk ik.

2024-12-18 08:57 UTC, JaroWMR commented on src/crepe/api/Rigidbody.h
> +		//! Enable collision handeling in collision system
Collision detectie is detecteren van collision.
Collision handeling is het verwerken van de collision.

Deze bool geeft aan dat je wilt dat het system de kinematic collision verwerkt.(handeld)
Ik zal in de doxygen aangeven dat je aangeeft dat de kinematic collision verwerkt word door het system als die active is,

2024-12-18 09:37 UTC, Max-001 requested changes
Ik ben weer verder gegaan met functioneel testen.

Alle collision werken (DYNAMIC - STATIC, etc.), mits `Transform::scale = 1`. Zodra ik de `Transform::scale` ergens anders op instel lijkt het dat het moment/punt van collision wél goed wordt gedetecteerd (dit geldt volgens mij niet bij box-box collision zodra `Transform::scale > 1`), maar het afhandelen van de collision gaat nog fout.
Hieronder een stukje test code:
``` CPP
		GameObject box_1 = this->new_object("box_1", "tag", vec2(-2, -4), 0, 0.5);
		Asset box_1_asset = Asset("asset/texture/square.png");
		box_1.add_component<Sprite>(box_1_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		box_1.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		box_1.add_component<BoxCollider>(vec2(1, 1));
		box_1.add_component<BehaviorScript>().set_script<ScriptBox>();

		GameObject circle_1 = this->new_object("ricle_1", "tag", vec2(2, -4), 0, 0.5);
		Asset circle_1_asset = Asset("asset/texture/circle.png");
		circle_1.add_component<Sprite>(circle_1_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		circle_1.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {-1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		circle_1.add_component<CircleCollider>(0.5);
		circle_1.add_component<BehaviorScript>().set_script<ScriptCircle>();

		GameObject circle_2 = this->new_object("ricle_2", "tag", vec2(-2.5, -1.5), 0, 0.5);
		Asset circle_2_asset = Asset("asset/texture/circle.png");
		circle_2.add_component<Sprite>(circle_2_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		circle_2.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		circle_2.add_component<CircleCollider>(0.5);
		circle_2.add_component<BehaviorScript>().set_script<ScriptCircle>();

		GameObject box_2 = this->new_object("box_2", "tag", vec2(2.5, -1.5), 0, 0.5);
		Asset box_2_asset = Asset("asset/texture/square.png");
		box_2.add_component<Sprite>(box_2_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		box_2.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {-1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		box_2.add_component<BoxCollider>(vec2(1, 1));
		box_2.add_component<BehaviorScript>().set_script<ScriptBox>();

		GameObject box_3 = this->new_object("box_3", "tag", vec2(-3, 1.5), 0, 0.5);
		Asset box_3_asset = Asset("asset/texture/square.png");
		box_3.add_component<Sprite>(box_3_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		box_3.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		box_3.add_component<BoxCollider>(vec2(1, 1));
		box_3.add_component<BehaviorScript>().set_script<ScriptBox>();

		GameObject box_4 = this->new_object("box_4", "tag", vec2(3, 1.5), 0, 0.5);
		Asset box_4_asset = Asset("asset/texture/square.png");
		box_4.add_component<Sprite>(box_4_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		box_4.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {-1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		box_4.add_component<BoxCollider>(vec2(1, 1));
		box_4.add_component<BehaviorScript>().set_script<ScriptBox>();

		GameObject circle_3 = this->new_object("ricle_3", "tag", vec2(-3.5, 4), 0, 0.5);
		Asset circle_3_asset = Asset("asset/texture/circle.png");
		circle_3.add_component<Sprite>(circle_3_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		circle_3.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		circle_3.add_component<CircleCollider>(0.5);
		circle_3.add_component<BehaviorScript>().set_script<ScriptCircle>();

		GameObject circle_4 = this->new_object("ricle_4", "tag", vec2(3.5, 4), 0, 0.5);
		Asset circle_4_asset = Asset("asset/texture/circle.png");
		circle_4.add_component<Sprite>(circle_4_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		circle_4.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {-1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		circle_4.add_component<CircleCollider>(0.5);
		circle_4.add_component<BehaviorScript>().set_script<ScriptCircle>();
```
Zodra ik deze code uitvoer, gebeurt het volgende:
https://github.com/user-attachments/assets/1716698d-7196-4362-b4ea-0a85334d58ed
Hieronder weer een nieuw stukje test code (ditmaal met `Transform::scale = 2`):
``` CPP
		GameObject box_1 = this->new_object("box_1", "tag", vec2(-2, -4), 0, 2);
		Asset box_1_asset = Asset("asset/texture/square.png");
		box_1.add_component<Sprite>(box_1_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		box_1.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		box_1.add_component<BoxCollider>(vec2(1, 1));
		box_1.add_component<BehaviorScript>().set_script<ScriptBox>();

		GameObject circle_1 = this->new_object("ricle_1", "tag", vec2(2, -4), 0, 2);
		Asset circle_1_asset = Asset("asset/texture/circle.png");
		circle_1.add_component<Sprite>(circle_1_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		circle_1.add_component<Rigidbody>(Rigidbody::Data{
			.gravity_scale = 0,
			.body_type = Rigidbody::BodyType::DYNAMIC,
			.linear_velocity = {-1, 0},
			.elastisity_coefficient = 0,
			.kinematic_collision = true,
		});
		circle_1.add_component<CircleCollider>(0.5);
		circle_1.add_component<BehaviorScript>().set_script<ScriptCircle>();

		GameObject circle_2 = this->new_object("ricle_2", "tag", vec2(-2.5, -1.5), 0, 2);
		Asset circle_2_asset = Asset("asset/texture/circle.png");
		circle_2.add_component<Sprite>(circle_2_asset, Sprite::Data{
			.sorting_in_layer = 0,
			.order_in_layer = 0,
			.size = vec2(1, 1),
			.angle_offset = 0,
			.scale_offset = 1,
			.position_offset = vec2(0, 0),
		});
		circle_2.add_component<Rigidbody>(Rigidbody::Data{
			.gr [...]

2024-12-18 10:04 UTC, Max-001 commented
Ik zie dat, zodra ik `Transform::rotation` aanpas, de colliders niet mee roteren. Dit is iets wat wel noodzakelijk is in Jetpack Joyride (voor de ronddraaiende zappers).
Onderstaande test code heb ik gebruikt:
...
En dit is het resultaat:
Uploading Ubuntu 64-bit - VMware Workstation 17 Player (Non-commercial use only) 2024-12-18 11-02-18.mp4…

2024-12-18 10:12 UTC, Max-001 commented
Ik wacht voor nu met verder testen. Het volgende wat ik namelijk wil gaan testen, is meerdere colliders op 1 GameObject en dan het GameObject schalen, roteren en transleren (ik verwacht dan dat de colliders mee schalen, roteren en transleren net als bij meerdere Sprites op 1 GameObject). Maar dit kan pas goed gaan als bovenstaande is opgelost.

2024-12-18 15:17 UTC, JaroWMR commented
> ```c++
> elastisity_coefficient
> ```
elastisity_coefficient kan negatief zijn en breekt het systeem. Dit kan ik helaas veranderen

2024-12-19 13:32 UTC, Max-001 approved these changes
Functioneel helemaal in orde

2024-12-19 13:36 UTC, Max-001 commented on src/test/CMakeLists.txt
Vergeet niet om de overige tests weer te activeren voordat er gemerged wordt.

2024-12-19 13:48 UTC, lonkaars requested changes
nog
- `git pull origin master`
- `git ls-files | xargs sed s/elastisity/elasticity/g -i`
- `make format`

2024-12-19 13:48 UTC, lonkaars commented on src/crepe/system/CollisionSystem.h
> +		BOTH
Code standaard: missende komma achter lijst

2024-12-19 13:48 UTC, lonkaars commented on src/crepe/system/CollisionSystem.cpp
>  }
Deze functie kan zelf de inverse van `info` berekenen:
```cpp
void CollisionSystem::call_collision_events(const CollisionInfo & info) {
	EventManager & emgr = this->mediator.event_manager;
	emgr.trigger_event(CollisionEvent{info}, info.self.transform.game_object_id);
	emgr.trigger_event(CollisionEvent{-info}, info.other.transform.game_object_id);
}
```

2024-12-19 13:48 UTC, lonkaars commented on src/crepe/system/CollisionSystem.cpp
>  }
Deze hele functie kan geschreven worden als
```cpp
CollisionSystem::CollisionInfo CollisionSystem::get_collision_info(const CollisionInternal & self, const CollisionInternal & other) const {
	return {
		.self = {
			.transform = self.info.transform,
			.rigidbody = self.info.rigidbody,
			.metadata = self.info.metadata,
		},
		.other = {
			.transform = other.info.transform,
			.rigidbody = other.info.rigidbody,
			.metadata = other.info.metadata,
		},
		.resolution = self.resolution,
		.resolution_direction = self.resolution_direction,
	};
}
```

2024-12-19 13:48 UTC, lonkaars commented on src/crepe/system/CollisionSystem.h
> +	 * \return returns resolution vector if collide otherwise returns {-1,-1}
Het valt mij op dit punt pas op dat `{-1, -1}` op meerdere plekken wordt gebruikt als een soort null waarde, maar kan dat niet veel beter `{0, 0}` of `{INFINITY, INFINITY}` zijn? De kans is klein dat hij ooit exact deze waarde zal hebben maar `{-1, -1}` is een zinnige resolutie vector toch?

2024-12-19 13:48 UTC, lonkaars commented on src/test/CMakeLists.txt
Dit moet nog teruggezet worden voordat deze PR gemerget kan worden

2024-12-19 15:56 UTC, JaroWMR commented on src/crepe/api/Rigidbody.h
> +		//! Enable static collision handeling for object colliding with kinematic object in collision system
Kinematic collision word normaal altijd script afgehandeld. Wat je aan kunt geven is dat kinematic objects de collision handling afgehandeldwordt door de collision system. Dus als een dynamisch object collide met de static obecjt (of kinematic met de bool) dan kan het dynamic object er niet doorheen. Ik ga de comment nog verbeteren omdat ik nog niet klaar was met de code netter maken. maar dat weet je in ieder geval waarvoor het is.

2024-12-19 19:04 UTC, lonkaars requested changes

2024-12-19 19:04 UTC, lonkaars commented on src/crepe/system/CollisionSystem.h
> +			ColliderType& collider;
Deze spacing klopt niet, moet je nog `make format` draaien?

2024-12-19 19:15 UTC, JaroWMR commented on src/crepe/system/CollisionSystem.cpp
> +	vec2 resolution{std::nanf(""), std::nanf("")};
gedaan

2024-12-19 19:16 UTC, JaroWMR commented on src/example/collisiontest.cpp
gedaan

2024-12-19 19:16 UTC, JaroWMR commented on src/crepe/system/CollisionSystem.cpp
> +			if(std::isnan(resolution.x) && std::isnan(resolution.y)) return false;
eigen functie gemaakt is_nan genoemd.

2024-12-19 19:21 UTC, JaroWMR commented
Voordat hij gemerged word wil @Max-001 nogmaals testen.
- [ ] Basis collision box-box
- [ ] Basis collision circle-box
- [ ] Basis collision circle-circle

Deze zijn genoeg om de verandering te testen (dynamic static is makkelijks)

2024-12-19 19:25 UTC, lonkaars commented on src/crepe/api/Vector2.hpp
> +    return std::isnan(x) && std::isnan(y);
Ik zie spaties, nog een keer `make format` draaien :pleading_face:

2024-12-19 19:26 UTC, lonkaars approved these changes

2024-12-19 19:28 UTC, JaroWMR commented on src/crepe/api/Vector2.hpp
> +    return std::isnan(x) && std::isnan(y);
je was te snel

2024-12-19 20:38 UTC, merged