Wouter/relative UI
lonkaars/crepe pull request #91
Opened 2024-12-18 13:44 UTC by Wboerenkamps

2024-12-18 17:07 UTC, lonkaars requested changes

2024-12-18 17:07 UTC, lonkaars commented on src/crepe/system/InputSystem.cpp
> +		}
Lege if statement?

2024-12-18 17:08 UTC, Wboerenkamps commented on src/crepe/system/InputSystem.cpp
> +		}
vegeten weg te halen :D

2024-12-19 12:49 UTC, lonkaars requested changes

2024-12-19 12:49 UTC, lonkaars commented on src/test/InputTest.cpp
> +	int offset_y = 200;
Kun je deze niet gewoon als `vec2 offset = {100, 200}` definiëren? Nu cast je impliciet een `int` naar `float` wat voor compileerwaarschuwingen zorgt.
<details>
<summary>patch</summary>

```diff
diff --git a/src/test/InputTest.cpp b/src/test/InputTest.cpp
index 25a1eeb..221faeb 100644
--- a/src/test/InputTest.cpp
+++ b/src/test/InputTest.cpp
@@ -36,11 +36,10 @@ public:
 	RenderSystem render{mediator};
 	EventManager event_manager{mediator};
 	//GameObject camera;
-	int offset_x = 100;
-	int offset_y = 200;
+	vec2 offset = {100, 200};
 protected:
 	void SetUp() override {
-		GameObject obj = mgr.new_object("camera", "camera", vec2{offset_x, offset_y}, 0, 1);
+		GameObject obj = mgr.new_object("camera", "camera", offset, 0, 1);
 		auto & camera
 			= obj.add_component<Camera>(ivec2{500, 500}, vec2{500, 500},
 										Camera::Data{.bg_color = Color::WHITE, .zoom = 1.0f});
@@ -76,8 +75,7 @@ TEST_F(InputTest, MouseDown) {
 	EventHandler<MousePressEvent> on_mouse_down = [&](const MousePressEvent & event) {
 		mouse_triggered = true;
 		//middle of the screen = 0,0
-		EXPECT_EQ(event.mouse_pos.x, offset_x);
-		EXPECT_EQ(event.mouse_pos.y, offset_y);
+		EXPECT_EQ(event.mouse_pos, offset);
 		EXPECT_EQ(event.button, MouseButton::LEFT_MOUSE);
 		return false;
 	};
@@ -101,8 +99,7 @@ TEST_F(InputTest, MouseUp) {
 	bool function_triggered = false;
 	EventHandler<MouseReleaseEvent> on_mouse_release = [&](const MouseReleaseEvent & e) {
 		function_triggered = true;
-		EXPECT_EQ(e.mouse_pos.x, offset_x);
-		EXPECT_EQ(e.mouse_pos.y, offset_y);
+		EXPECT_EQ(e.mouse_pos, offset);
 		EXPECT_EQ(e.button, MouseButton::LEFT_MOUSE);
 		return false;
 	};
@@ -125,8 +122,7 @@ TEST_F(InputTest, MouseMove) {
 	bool function_triggered = false;
 	EventHandler<MouseMoveEvent> on_mouse_move = [&](const MouseMoveEvent & e) {
 		function_triggered = true;
-		EXPECT_EQ(e.mouse_pos.x, offset_x);
-		EXPECT_EQ(e.mouse_pos.y, offset_y);
+		EXPECT_EQ(e.mouse_pos, offset);
 		EXPECT_EQ(e.mouse_delta.x, 10);
 		EXPECT_EQ(e.mouse_delta.y, 10);
 		return false;
@@ -199,8 +195,7 @@ TEST_F(InputTest, MouseClick) {
 	EventHandler<MouseClickEvent> on_mouse_click = [&](const MouseClickEvent & event) {
 		on_click_triggered = true;
 		EXPECT_EQ(event.button, MouseButton::LEFT_MOUSE);
-		EXPECT_EQ(event.mouse_pos.x, offset_x);
-		EXPECT_EQ(event.mouse_pos.y, offset_y);
+		EXPECT_EQ(event.mouse_pos, offset);
 		return false;
 	};
 	event_manager.subscribe<MouseClickEvent>(on_mouse_click);
```
</details>

2024-12-19 18:14 UTC, heavydemon21 commented on src/crepe/system/InputSystem.cpp
Ik zie hier oproepen van get_transform maar zie hier nergens const staan. kijk er nog even overheen en maak de code const waar het kan

2024-12-20 08:11 UTC, heavydemon21 approved these changes

2024-12-20 10:19 UTC, merged